### PR TITLE
Extensions icon and dark theme support

### LINKED ISSUE #29: [Enhancement] The "TAAR" doorhanger should respect the browser's dark theme color
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "TAAR v3" add-on (downloaded from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546) installed.
- Create the following prefs in the "about:config" page:
	- "shieldStudy.logLevel" as string and set it to "All";
	- "extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"
- Have the browser's dark theme enabled from "about:addons>Themes>Dark".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to three websites and observe the doorhanger's background color.

**[Expected result]:**
- The doorhanger's background is dark and the text is white.

**[Actual result]:**
- The doorhanger's background is white and the text is black.

**[Notes]:**
- All other doorhangers/menus respect the dark theme color, considering this we should do the same for the sake of the consistency.
- Attached a screen recording of the issue:
rec of the issue

### LINKED ISSUE #30: Change Firefox icon in doorhanger to puzzle piece icon
Was alerted that we're using the wrong icon in the door hanger, as seen here:
screen shot 2018-06-28 at 9 34 04 am

It needs to be changed to the puzzle piece icon. png is attached to this issue.
[addonicon.zip](https://github.com/motin/taar-experiment-v3-shield-study/files/2146259/addonicon.zip)

### PR DESCRIPTION
**Pull request by motin**
Fixes https://github.com/motin/taar-experiment-v3-shield-study/issues/30
Fixes https://github.com/motin/taar-experiment-v3-shield-study/issues/29
Dark theme fix inspired by https://github.com/mozilla/side-view/pull/239/files

Default theme:
example_domain

Dark theme:
example_domain

### CODE REVIEW

**Comment by mlopatka** [comment]
@sevaan @pwalm 
who from UX can review this PR before we merge it in?
A fly-by r+ in the comments is fine as well.

**Comment by sevaan** [comment]
Hi all, seeing these mocks makes me realize the icon should probably be green (#12BC00), especially since it's a promotional message, I think it would make it more eye-catching.

Can we also confirm the green icon in the URL bar matches? Doesn't quite look like the right green in there to me.

Flagging @motin 

Thanks everyone, looks great!

**Comment by pwalm** [comment]
If green is the way to go in the browser, then that is fine with me. As for the green, I think `#30e60b` is the right one. I've taken it from the design system, since we don't really have a brand green for Add-ons.

**Comment by motin** [comment]
@pwalm, @sevaan: This is in green using #30e60b:

Light:
example_domain_and_browser_console_and_1__plugin-container

Dark:
example_domain_and_browser_console_and_bear

Let me know if this shade is the one to use, thanks :)

**Comment by pwalm** [comment]
Ship it! 🚢

**Pull request merged**
