### PR TITLE
Check for PB mode before showing panel

### PR DESCRIPTION
**Pull request by biancadanforth**
Note: The page visited counter will stop incrementing while the user has a PB window open; once the window closes, it will start incrementing again in normal windows.

### CODE REVIEW

**Comment by mlopatka** [comment]
xpi has been tested locally an uploaded for signing. It would be nice to merge this back into master for consistency, but there is no rush.

**Comment by biancadanforth** [comment]
I was developing off of `master` not the `develop` branch; I guess someone changed the branch I'm merging into to `develop` instead, so that's what all these other commits (old commits motin made on the `develop` branch) are about. @motin is the `develop` branch the branch you were using to build the XPI for deployment?

**Comment by biancadanforth** [comment]
Looks to be the diff I'm expecting, so I'll move ahead anyway.

**Comment by motin** [comment]
Thanks Bianca :) These fixes have been included and tagged in the master branch relative to each version release (e5827530dfce23b094dceec028a75ea5f9b0c2f5, 261724b4495512ae58e711699ba2e0c4a9af8158, d5ebdee86eba08cf9a55970ed5d573bbd62d8391)

**Pull request closed without merging**
